### PR TITLE
Create get_zenodo_dir.R

### PR DESCRIPTION
**Pull request by HedvigS**
suggestion for function. It just downloads dirs from Zenodo, for example CLDF-data.

### CODE REVIEW

**Comment by HedvigS** [comment]
I found a small bug with the dir moving, fixing now.

**Comment by HedvigS** [comment]
fixed

**Comment by SimonGreenhill** [comment]
This is now implemented in rcldf as a transparent download of cldf datasets from URLs e.g. 

```r
o <- cldf('https://github.com/lexibank/sabor/archive/refs/tags/v1.0.zip')

gb <- cldf("https://github.com/grambank/grambank/archive/refs/tags/v1.0.3.zip")
gb$tables$LanguageTable
```

Also note that my implementation caches the download so rerunning this multiple times re-uses the cached download

```r
gb <- cldf("https://github.com/grambank/grambank/archive/refs/tags/v1.0.3.zip")
gb <- cldf("https://github.com/grambank/grambank/archive/refs/tags/v1.0.3.zip")
```

**Comment by HedvigS** [comment]
Why fetch GitHub instead of Zenodo?

**Comment by HedvigS** [comment]
When I run the code, I get:

```
> gb <- cldf("https://github.com/grambank/grambank/archive/refs/tags/v1.0.3.zip")
Downloading to cache dir: /Users/skirgard/Library/Caches/org.R-project.R/R/rcldf/2df6aba385d497b74ec8df7c222c61bb
Error in resolve_path(mdpath) :
no metadata JSON file found in /Users/skirgard/Library/Caches/org.R-project.R/R/rcldf/2df6aba385d497b74ec8df7c222c61bb```

**Comment by HedvigS** [comment]
Solved it, the error message didn't say but there were more functions I needed to load. Working now.

**Pull request closed without merging**
